using AutoGenerateData.Generator.Base;
using AutoGenerateData.Models;
using AutoGenerateData.Models.Interface;
using Bogus;
using System;

namespace AutoGenerateData.Generator.Items
{
	public class GeneratorAccount : Creator
	{
		public override IEntity FactoryMethod(Faker faker)
		{
			var accout = new Account()
			{
				Id = Guid.NewGuid(),
				CreatedOn = faker.Date.Soon(),
				ModifiedOn = faker.Date.Soon(),
				ProcessListeners = 0,
				GPSE = "VB",
				GPSN = "VB",
				Name = faker.Company.CompanyName(),
				AlternativeName = faker.Company.CompanySuffix(),
				Phone = faker.Phone.PhoneNumber(),
				AdditionalPhone = faker.Phone.PhoneNumber(),
				Address = faker.Address.FullAddress(),
				Fax = faker.Address.BuildingNumber(),
				Web = faker.Internet.Email(),
				Zip = faker.Address.ZipCode(),
				Description = faker.Lorem.Slug(),
				Code = faker.Finance.Account(),
				Notes = faker.Lorem.Lines(),
				Completeness = 100
			};

			return accout;
		}
	}
}
