using AutoGenerateData.Generator.Base;
using AutoGenerateData.Models;
using AutoGenerateData.Models.Interface;
using Bogus;
using System;

namespace AutoGenerateData.Generator.Items
{
	public class GeneratorContact : Creator
	{
		public override IEntity FactoryMethod(Faker faker)
		{
			var contact = new Contact()
			{
				Id = Guid.NewGuid(),
				CreatedOn = faker.Date.Soon(),
				ModifiedOn = faker.Date.Soon(),
				ProcessListeners = 0,
				GPSE = "VB",
				GPSN = "VB",
				Name = faker.Name.FirstName(),
				Surname = faker.Name.LastName(),
				MiddleName = faker.Name.FindName(),
				JobTitle = faker.Name.JobTitle(),
				Address = faker.Address.FullAddress(),
				Zip = faker.Address.ZipCode(),
				Phone = faker.Phone.PhoneNumber(),
				MobilePhone = faker.Phone.PhoneNumber(),
				HomePhone = faker.Phone.PhoneNumber(),
				Email = faker.Internet.Email(),
				Twitter = faker.Internet.UserName(),
				Facebook = faker.Internet.UserName(),
				Skype = faker.Internet.UserName(),
				
				
			};

			return contact;
		}
	}
}
