using AutoGenerateData.Generator.Base;
using AutoGenerateData.Models.Interface;
using Bogus;
using System;

namespace AutoGenerateData.Generator.Items
{
	class GeneratorContact : Creator
	{
		public override IEntity FactoryMethod(Faker faker)
		{
			throw new NotImplementedException();
		}
	}
}
