using AutoGenerateData.Generator.Base;
using EFCore.BulkExtensions;
using AutoGenerateData.Models.Db;
using AutoGenerateData.Models.Interface;
using Bogus;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;

namespace AutoGenerateData.Generator
{
	public class GenerateItems
	{
		private Faker _faker;
		private GenerateDbContext _db;
		private List<IEntity> _listEntity;
		private int _count;

		private const int MaxInChunk = 100;
		
		public delegate void ProgressHedler(int CountItems);
		public event ProgressHedler	Notify;

		public GenerateItems(int countItems, GenerateDbContext db) {
			_faker = new Faker("ru");
			_count = countItems;
			_db = db;		
			_listEntity = new List<IEntity>();
		}

		public void RunGenerator(Creator creteEntity, bool saveToDb = true) {

			Creator creator = creteEntity;

			for (var i = 0; i < _count; i++)
			{
				if (_listEntity.Count == MaxInChunk && saveToDb) {
					SaveToDb();
				}
				
				var entity = creator.FactoryMethod(_faker);
				_listEntity.Add(entity);
				
			}

			if (_listEntity.Any() && saveToDb)
			{
				SaveToDb();
			}
		}

		public void RunGeneratorAsync(Creator creteEntity)
		{

			Task task1 = new Task(() => { Console.WriteLine("Task1 is executed"); });
			task1.Start();

			Task task2 = Task.Factory.StartNew(() => Console.WriteLine("Task2 is executed"));

			Task task3 = Task.Run(() => Console.WriteLine("Task3 is executed"));
			
		}

		public List<IEntity> GetEntiesList() {
			return _listEntity;
		}

		private void SaveToDb() {

			if (_listEntity.Any()) {
				_db.BulkInsert(_listEntity);	
				_db.SaveChanges();
				Notify.Invoke(_listEntity.Count);
				_listEntity.Clear();
			}

		}


	}
}
