using AutoGenerateData.Generator;
using AutoGenerateData.Generator.Base;
using AutoGenerateData.Generator.Items;
using AutoGenerateData.Ui;
using AutoGenerateData.Models.Db;
using System;
using System.Diagnostics;

namespace AutoGenerateData
{
	class Program
	{
		static void Main(string[] args)
		{
			try
			{
				using (var context = new GenerateDbContext())
				{

					Console.WriteLine("Auto Generator");

					var creator = UiProcess.SelectCreator();
					var count = UiProcess.SetCountItems();				

					GenerateItems generateItems = new GenerateItems(count, context);
					//GenerateItems generateItems = new GenerateItems(count);
					generateItems.Notify += UiProcess.ProgressImport;

					
					Stopwatch stopwatch = new Stopwatch();

					stopwatch.Start();

					generateItems.RunGenerator(creator);

					stopwatch.Stop();

					UiProcess.GetResultMessage(stopwatch);

				}
			}
			catch (Exception ex)
			{
				UiProcess.GetErrorMessage(ex.Message);
			}

		}
	}
}
