using AutoGenerateData.Generator;
using AutoGenerateData.Generator.Items;
using AutoGenerateData.Models.Db;
using System;

namespace AutoGenerateData
{
	class Program
	{
		private static int CountImported = 0;

		static void Main(string[] args)
		{

			try
			{
				using (var context = new GenerateDbContext())
				{

					Console.WriteLine("Auto Generator");
					Console.Write("Count items for import: ");

					int count = 0;
					if (!Int32.TryParse(Console.ReadLine(), out count))
					{
						count = 10;
					};

					GenerateItems generateItems = new GenerateItems(count, context);
					generateItems.Notify += ProgressImport;
					generateItems.RunGenerator(new GeneratorAccount());

					context.Account.AddRange();

				}
			}
			catch (Exception ex) {

				Console.ForegroundColor = ConsoleColor.Red;
				Console.WriteLine(ex.Message);
				Console.ForegroundColor = ConsoleColor.White;
			}

			Console.ForegroundColor = ConsoleColor.Green;
			Console.WriteLine($"{CountImported} items imported successfully!!!");
			Console.ForegroundColor = ConsoleColor.White;
			Console.ReadKey();
			
		}

		private static void ProgressImport(int countItems) {
			CountImported += countItems;
			Console.WriteLine($"Count imported items: {CountImported}");
		}
	}
}
