using AutoGenerateData.Generator;
using AutoGenerateData.Generator.Base;
using AutoGenerateData.Generator.Items;
using AutoGenerateData.Ui;
using AutoGenerateData.Models.Db;
using System;
using System.Diagnostics;

namespace AutoGenerateData
{
	class Program
	{
		static void Main(string[] args)
		{
			try
			{
				

				using (var context = new GenerateDbContext())
				{

					Console.WriteLine("Auto Generator");

					while (true) {

						UiProcess.CleareImportedCount();

						var creator = UiProcess.SelectCreator();
						var count = UiProcess.SetCountItems();

						GenerateItems generateItems = new GenerateItems(count, context);
						generateItems.Notify += UiProcess.ProgressImport;

						Stopwatch stopwatch = new Stopwatch();

						stopwatch.Start();

						generateItems.RunGenerator(creator);

						stopwatch.Stop();

						UiProcess.GetResultMessage(stopwatch);
						
						if (!UiProcess.GoOn()) {
							return;
						} 
					}	
				}
			}
			catch (Exception ex)
			{
				UiProcess.GetErrorMessage(ex.Message);
			}

			Console.ReadKey();

		}
	}
}
