namespace AutoGenerateData.Models
{
	public class Account : Entity
	{		
		public string Name { set; get; }
		public string Description { get; set; }
		public string Code { get; set; }
		public string Phone { get; set; }
		public string AdditionalPhone { get; set; }
		public string Fax { get; set; }
		public string Web { get; set; }
		public string Address { get; set; }
		public string Zip { get; set; }
		public string Notes { get; set; }
		public string AlternativeName { get; set; }
		public string GPSN { get; set; }
		public string GPSE { get; set; }
		public int Completeness { get; set; }

	}
}
