namespace AutoGenerateData.Models
{
	public class Contact : Entity
	{
		public string Name { get; set; }
		public string Description { get; set; }		
		public string Dear { get; set; }
		public string JobTitle { get; set; }
		public string Phone { get; set; }
		public string MobilePhone { get; set; }
		public string HomePhone { get; set; }
		public string Skype { get; set; }
		public string Email { get; set; }
		public string Address { get; set; }
		public string Zip { get; set; }
		public bool DoNotUseEmail { get; set; }
		public bool DoNotUseCall { get; set; }
		public bool DoNotUseFax { get; set; }
		public bool DoNotUseSms { get; set; }
		public bool DoNotUseMail { get; set; }
		public string Notes { get; set; }
		public string Facebook { get; set; }
		public string LinkedIn { get; set; }
		public string Twitter { get; set; }
		public string FacebookId { get; set; }
		public string LinkedInId { get; set; }
		public string TwitterId { get; set; }	
		public string Surname { get; set; }
		public string GivenName { get; set; }
		public string MiddleName { get; set; }
		public bool Confirmed { get; set; }
		public bool IsNonActualEmail { get; set; }
		public int RId { get; set; }
		public string GPSN { get; set; }
		public string GPSE { get; set; }
		public int Completeness { get; set; }

	}
}
