using AutoGenerateData.Models.Interface;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AutoGenerateData.Models
{
	public class Entity: IEntity
	{
		[Key]
		public Guid Id { get; set; }
		public DateTime CreatedOn { get; set; }

		[ForeignKey("CreatedBy")]
		public Guid? CreatedById { get; set; }
		public Contact CreatedBy { get; set; }
		public DateTime ModifiedOn { get; set; }

		[ForeignKey("ModifiedBy")]
		public Guid? ModifiedById { get; set; }
		public Contact ModifiedBy { get; set; }
		public int ProcessListeners { get; set; }
	}
}
