using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace AutoGenerateData.Models.Db
{
	public class GenerateDbContext : DbContext
	{

		public GenerateDbContext() {

			Database.EnsureCreated();
		}

		public DbSet<Contact> Contact { get; set; }
		public DbSet<Account> Account { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
		
			IConfigurationRoot config = GetConfiguration().Build();

			optionsBuilder.UseSqlServer(config.GetConnectionString("DefaultConnection"));
		}

		public static IConfigurationBuilder GetConfiguration() { 
			return new ConfigurationBuilder()
						.SetBasePath(Directory.GetCurrentDirectory())
						.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
		}
		
	}
}
