using AutoGenerateData.Generator;
using AutoGenerateData.Generator.Items;
using AutoGenerateData.Models.Db;
using NUnit.Framework;

namespace AutoGenerateNUnitTest
{
	public class Tests
	{
		GenerateItems generateItems;
		int Count = 10;

		[SetUp]
		public void Setup()
		{
			using (var context = new GenerateDbContext()) {
				generateItems = new GenerateItems(Count, context);
			}
		}

		[Test]
		public void GenerateAccounts()
		{
			generateItems.RunGenerator(new GeneratorAccount(), false);
			var resultArrey = generateItems.GetEntiesList();
		}

		[Test]
		public void GenerateContacts()
		{
			generateItems.RunGenerator(new GeneratorContact(), false);
			var resultArrey = generateItems.GetEntiesList();
		}
	}
}